<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>$(MSBuildProjectName.Replace("-dev", ""))</AssemblyName>
    <RootNamespace>$(MSBuildProjectName.Replace("-dev", ""))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="6.0.25" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\MDD4All.DME.ViewModels\src\MDD4All.DME.ViewModels-dev\MDD4All.DME.ViewModels-dev.csproj" />
    <ProjectReference Include="..\..\..\MDD4All.UI.Blazor\src\MDD4All.UI.Blazor\MDD4All.UI.Blazor-dev.csproj" />
    <ProjectReference Include="..\..\..\MDD4All.UI.BlazorComponents\src\MDD4All.UI.BlazorComponents\MDD4All.UI.BlazorComponents-dev.csproj" />
    <ProjectReference Include="..\..\..\MDD4All.Reflection.TypeAnalyzer\src\MDD4All.Reflection.TypeAnalyzer\MDD4All.Reflection.TypeAnalyzer-dev.csproj" />
  </ItemGroup>

</Project>
